---
# Common RDS instance parameters
DbEngine: "mysql"
DbLicenseModel: "general-public-license"
DbMasterUsername: "rootmaster"
DbMasterPassword: "dbrootpass"
DbBackupWindow: "12:37-13:07"
DbMaintenanceWindow: "thu:03:00-thu:03:45"

# a dict of RDS instances to create
db_dict:
  dbdev:
    DbVersion: "5.5.46"
    DbVolSize: 5
    DbType: "db.t2.medium"
    DbPort: "3306"
    DbOptionSet: "default:mysql-5-5"
    DbSnapshotRetention: "3"
    DbParamGroupName: "default.mysql5.5"
